In [ ]:
harsh =[[1,2,3,4,5],[213,42,12],[2,4,5,64]]
sum = (harsh[0][0] + harsh[-1][-1] )

print (sum)

65

**Numpy array and Basic **

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np

harsh = "helloBOi Kya Hal hai "
oi = "hello python "

dir (harsh)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [ ]:
dir (np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfortranarray',
 'asin',
 'asinh',
 'asmatrix',
 'astype',
 'atan',
 'atan2',
 'atanh',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_count',
 'bitwise_invert',
 'bitwise_left_shift',
 'bitwise_not',
 'bitwise_or',
 'bitwise_right_shift',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_shapes',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'bytes_',
 'c_',
 'can_cast',
 'cbrt',
 'cdouble',
 'ceil',
 'char',
 'character',
 'choose',
 'clip',
 'clongdouble',
 'column_stack',
 'common_type',
 'complex128',
 'complex256',
 'complex64',
 'complexfloating',
 'compress',
 'concat',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'divide',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'dtypes',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exceptions',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'f2py',
 'fabs',
 'fft',
 'fill_diagonal',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float128',
 'float16',
 'float32',
 'float64',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'frexp',
 'from_dlpack',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'inner',
 'insert',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isdtype',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issubdtype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'long',
 'longdouble',
 'longlong',
 'ma',
 'mask_indices',
 'matmul',
 'matrix',
 'matrix_transpose',
 'max',
 'maximum',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mod',
 'modf',
 'moveaxis',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'ndarray',
 'ndenumerate',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'number',
 'object_',
 'ogrid',
 'ones',
 'ones_like',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'permute_dims',
 'pi',
 'piecewise',
 'place',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'pow',
 'power',
 'printoptions',
 'prod',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'row_stack',
 's_',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctypeDict',
 'searchsorted',
 'select',
 'set_printoptions',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'show_runtime',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'sinh',
 'size',
 'sort',
 'sort_complex',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str_',
 'strings',
 'subtract',
 'sum',
 'swapaxes',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'transpose',
 'trapezoid',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typecodes',
 'typename',
 'typing',
 'ubyte',
 'ufunc',
 'uint',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulong',
 'ulonglong',
 'union1d',
 'unique',
 'unique_all',
 'unique_counts',
 'unique_inverse',
 'unique_values',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vecdot',
 'vectorize',
 'void',
 'vsplit',
 'vstack',
 'where',
 'zeros',
 'zeros_like']

In [ ]:
print(f"Original string: {harsh}")
print(f"Uppercase: {harsh.upper()}")
print(f"Lowercase: {harsh.lower()}")
print(f"Capitalized: {harsh.capitalize()}")
print(f"Replaced 'BOi' with 'Friend': {harsh.replace('BOi', 'Friend')}")
print (np.char.center(harsh,20,fillchar='-'))

words = harsh.split()
print(f"Split into words: {words}")
print(f"Joined words: {' '.join(words)}")

Original string: helloBOi Kya Hal hai
Uppercase: HELLOBOI KYA HAL HAI
Lowercase: helloboi kya hal hai
Capitalized: Helloboi kya hal hai
Replaced 'BOi' with 'Friend': helloFriend Kya Hal hai
Split into words: ['helloBOi', 'Kya', 'Hal', 'hai']
Joined words: helloBOi Kya Hal hai

In [ ]:
import numpy as np

numpy_harsh = np.array([harsh])

print(f"Original string (NumPy array): {numpy_harsh}")
print(f"Uppercase: {np.char.upper(numpy_harsh)}")
print(f"Lowercase: {np.char.lower(numpy_harsh)}")
print(f"Capitalized: {np.char.capitalize(numpy_harsh)}")
print(f"Replaced 'BOi' with 'Friend': {np.char.replace(numpy_harsh, 'BOi', 'Friend')}")
print(f"Replaced 'Boi' with ' Friend': {np.char.replace(numpy_harsh, 'BOi', '**Friend')}")
print(np.char.center(harsh,20,fillchar='-'))


numpy_words = np.char.split(numpy_harsh)
print(f"Split into words: {numpy_words}")

joined_numpy_words = [' '.join(words_list) for words_list in numpy_words]
print(f"Joined words: {joined_numpy_words[0]}")

Original string (NumPy array): ['helloBOi Kya Hal hai ']
Uppercase: ['HELLOBOI KYA HAL HAI ']
Lowercase: ['helloboi kya hal hai ']
Capitalized: ['Helloboi kya hal hai ']
Replaced 'BOi' with 'Friend': ['helloFriend Kya Hal hai ']
Replaced 'Boi' with ' Friend': ['hello**Friend Kya Hal hai ']
helloBOi Kya Hal hai
Split into words: [list(['helloBOi', 'Kya', 'Hal', 'hai'])]
Joined words: helloBOi Kya Hal hai

In [ ]:
print(np.char.center(numpy_words, 20, fillchar='-'))

NameError: name 'np' is not defined

DAY - 3

In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(arr_1d.size)   # . SIZE is used to check for the sixe of array

[1 2 3 4 5]
5

In [ ]:
print(arr_1d.ndim) # . ndim IS used to know the number of dimensions of array

1

In [ ]:
# 2D array and opr
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.size)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
6
2

In [ ]:
print(arr_2d.shape) # .shape it shoe the number of ROWS AND CLOUMNS of array

In [ ]:
# 3d Array And Opr
arr_3d = np.array([[[1,2,3,4],[5,6,7,8]]
                   ,
                    [[10,20,30,40],[50,60,70,80]]])

print(arr_3d)
print(arr_3d.size)
print(arr_3d.ndim)
print(arr_3d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
16
3
(2, 2, 4)
int64

In [ ]:
print(arr_3d.dtype) #.dtype Is Used To Display The type of data stored in dymensions

In [ ]:
#ONES IN NUMPY
mx_ones = np.ones(5)

print(mx_ones)

[1. 1. 1. 1. 1.]

In [ ]:
#ONES IN NUMPY
# `np.ones((rows, columns))` creates a new array of the specified shape (rows, columns)
# and fills it with ones. The default data type is float.
mx_ones = np.ones((3,2))

print(mx_ones)
print(mx_ones.dtype)
mx_ones.dtype=int
print(mx_ones)
print(mx_ones.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[1 1]
 [1 1]
 [1 1]]
int64

In [ ]:
mx_zeros  = np.zeros((3,3))
print(mx_zeros)
print(mx_zeros.dtype)
mx_zeros.dtype=int
print(mx_zeros)
print(mx_zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64

In [ ]:
line = np.linspace(0, 100, 20)
print(line)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]

In [ ]:
print(arr_3d.ravel()) # returns the array, flattened

[ 1  2  3  4  5  6  7  8 10 20 30 40 50 60 70 80]

In [ ]:
print(arr_3d.flatten()) # returns the array, flattened

[ 1  2  3  4  5  6  7  8 10 20 30 40 50 60 70 80]

In [ ]:
print(arr_3d.transpose())

[[[ 1 10]
  [ 5 50]]

 [[ 2 20]
  [ 6 60]]

 [[ 3 30]
  [ 7 70]]

 [[ 4 40]
  [ 8 80]]]

In [ ]:
np_lst = [1,2,3,45]

### `np.vstack()` - Vertical Stacking

`np.vstack()` stacks arrays in sequence vertically (row-wise). This means it concatenates arrays along the first axis (rows). The arrays must have the same number of columns (or the same shape along all but the first axis) to be vertically stacked.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

v_stack = np.vstack((arr1, arr2))
print("\nVertical Stack (vstack):")
print(v_stack)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Vertical Stack (vstack):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

### `np.hstack()` - Horizontal Stacking

`np.hstack()` stacks arrays in sequence horizontally (column-wise). This means it concatenates arrays along the second axis (columns). The arrays must have the same number of rows (or the same shape along all but the second axis) to be horizontally stacked.

In [ ]:
import numpy as np

arr3 = np.array([[1, 2,3,4,2], [3, 4,6,3,1]])
arr4 = np.array([[5, 6,6,7,5], [7, 8,14,5,6]])

print("Array 3:")
print(arr3)
print("\nArray 4:")
print(arr4)

h_stack = np.hstack((arr3, arr4))
print("\nHorizontal Stack (hstack):")
print(h_stack)

Array 3:
[[1 2 3 4 2]
 [3 4 6 3 1]]

Array 4:
[[ 5  6  6  7  5]
 [ 7  8 14  5  6]]

Horizontal Stack (hstack):
[[ 1  2  3  4  2  5  6  6  7  5]
 [ 3  4  6  3  1  7  8 14  5  6]]

**Mathemetical Fundamentals**

In [ ]:
import numpy as np

# minimum and maximum
mn_arr = np.minimum(arr3, arr4)
mx_arr = np.maximum(arr3, arr4)

print("Minimum ")
print(mn_arr)

print("\n Maximum")
print(mx_arr)

print("\nSum of element-wise min and max arrays:")
print(mn_arr + mx_arr)

print("\nSubtraction of element-wise min and max arrays:")
print(mn_arr - mx_arr)

print("\nmultiplication of element-wise min and max arrays:")
print (mn_arr * mx_arr)

Minimum
[[1 2 3 4 2]
 [3 4 6 3 1]]

 Maximum
[[ 5  6  6  7  5]
 [ 7  8 14  5  6]]

Sum of element-wise min and max arrays:
[[ 6  8  9 11  7]
 [10 12 20  8  7]]

Subtraction of element-wise min and max arrays:
[[-4 -4 -3 -3 -3]
 [-4 -4 -8 -2 -5]]

multiplication of element-wise min and max arrays:
[[ 5 12 18 28 10]
 [21 32 84 15  6]]

In [ ]:
  import numpy as np
  arr1 = np.array([1,2,3,4])
  arr2 = np.array([5])
  res = arr1+arr2
  print(res)

ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [ ]:
  import numpy as np
  arr1 = np.array([[1,2,3],[3,5,6]])
  arr2 = np.array([5])
  res = arr1*arr2
  print("multiplication in 2D")
  print(res)

multiplication
[[ 5 10 15]
 [15 25 30]]

In [ ]:
  import numpy as np
  arr1 = np.array([[[1,2,3],[3,5,6]]
                   ,[[1,34,5],[2,4,5]]])
  arr2 = np.array([5])
  res = arr1*arr2
  print("multiplication in 3D")
  print(res)

multiplication in 3D
[[[  5  10  15]
  [ 15  25  30]]

 [[  5 170  25]
  [ 10  20  25]]]

In [ ]:
import numpy as np

arrrr = np.array([1, 2, 3, 4, 5, -2, -14, -14, -34])

positive = arrrr[arrrr > 0]
negative = arrrr[arrrr < 0]

print("Positive:", positive)
print("Negative:", negative)

Positive: [1 2 3 4 5]
Negative: [ -2 -14 -14 -34]

MASKING IN PYTHON VERY IMPORT BOI

In [ ]:
# 1D

arrrr = np.array([1, 2, 3, 4, 5, -2, -14, -14, -34])
ans = (arrrr[arrrr < 0])
print(f"Print The index Using Masking Metheod {ans}")

Print The index Using Masking Metheod [ -2 -14 -14 -34]

In [ ]:
import numpy as np

#2D
arrrr = np.array([[1, 2, 3, 4, 5, -2, -14, -14, -34],
                  [2, 4, 5, 6, 7, -1, 4, -46, -67]])
ans_index = arrrr[arrrr < 0]

print(f"Print The index Using Masking Metheod {ans_index}")

Print The index Using Masking Metheod [ -2 -14 -14 -34  -1 -46 -67]

In [ ]:
import numpy as np

arrrr = np.array([1, 2, 3, 4, 5, -2, -14, -14, -34])

positive = list(filter(lambda x: x is not None,
                       map(lambda x: x if x > 0 else None, arrrr)))

negative = list(filter(lambda x: x is not None,
                       map(lambda x: x if x < 0 else None, arrrr)))

print("Positive:", positive)
print("Negative:", negative)

**DAY 4 **

WHAT IS PANDAS ?
WHY PANDAS ?
What Is Series ?
WHAT IS DataFrame?
Reading Data ?
Exploring Data
Selecting Data
Modifying Data
Sorting Data
Agrigating Data
Handling Missing Data
Applying Function

**What Is Pandas ?? **

In [ ]:
import pandas as pd
sr = [1,2,5,4,1,2,153,51]
sr_1 = pd.Series(sr)

print(sr)
print(sr_1)

[1, 2, 5, 4, 1, 2, 153, 51]
0      1
1      2
2      5
3      4
4      1
5      2
6    153
7     51
dtype: int64

In [ ]:
sr = [[1,2,5,4,1,2,153,51],[34,6,32,1,4,6]]
lab = ['a','b','c','d','e','f','g','h']
sr_1 = pd.Series(sr)

print(sr)
print(sr_1)
print(type(sr_1))

[[1, 2, 5, 4, 1, 2, 153, 51], [34, 6, 32, 1, 4, 6]]
0    [1, 2, 5, 4, 1, 2, 153, 51]
1           [34, 6, 32, 1, 4, 6]
dtype: object
<class 'pandas.core.series.Series'>

**DATA FRAME**

In [ ]:
data2 = [[10,20,30,40],[50,60,70,80]]

df2 = pd.DataFrame(data2)
print(df2)
print(type(df2))

    0   1   2   3
0  10  20  30  40
1  50  60  70  80
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df2 = pd.DataFrame(data2,columns=['a','b','c','d'],index = ['A','B'])
print(df2)
print(type(df2))

    a   b   c   d
A  10  20  30  40
B  50  60  70  80
<class 'pandas.core.frame.DataFrame'>

In [ ]:
data = [('harsh ',89 ),('oihoi',34),('waiwai',35 )]
d = pd.DataFrame(data,columns=['Name','Age'])
print(d)

     Name  Age
0  harsh    89
1   oihoi   34
2  waiwai   35

In [ ]:
data3 = {
    'roll': [1,2,4,5,6],
    'name' : ['harsh','jumla','kaka','sidhe','mot']
}

d = pd.DataFrame(data3)
print(d)

   roll   name
0     1  harsh
1     2  jumla
2     4   kaka
3     5  sidhe
4     6    mot

In [ ]:
nested_list = [['harsh',10],['dishum' , 36],['oihoihoi',154]]
data1 = pd.DataFrame(nested_list,columns=['Name','Age'])
print(data1)

       Name  Age
0     harsh   10
1    dishum   36
2  oihoihoi  154

In [ ]:
import numpy as np

d1 = np.array([1,2,3,4,5])
d2 = np.array([98,6,46,78,34])
Data_fr = {
    'df1':d1,
    'df2':d2
}
df = pd.DataFrame(Data_fr)
print(df)

   df1  df2
0    1   98
1    2    6
2    3   46
3    4   78
4    5   34

In [ ]:
import numpy as np

d1 = np.array([1,2,3,4,5])
d2 = np.array([98,6,46,78,34])
Data_fr = {
    'df1':d1,
    'df2':d2
}
df = pd.DataFrame(Data_fr)
print(df)

In [ ]:
import pandas as pd


name = pd.read_csv("/content/sample_data/name.csv")
json_data = pd.read_json("/content/sample_data/colors.json")

display(name)

display(json_data)

              value
0           barjraj
1      ramdin verma
2   sharat chandran
3   birender mandal
4              amit
..              ...
95           deepak
96            rahul
97        abhishekh
98  shelender yadav
99           sanjay

[100 rows x 1 columns]

                                               colors
0   {'name': 'Black', 'hex': '#000000', 'rgb': {'r...
1   {'name': 'White', 'hex': '#FFFFFF', 'rgb': {'r...
2   {'name': 'Red', 'hex': '#FF0000', 'rgb': {'r':...
3   {'name': 'Green', 'hex': '#00FF00', 'rgb': {'r...
4   {'name': 'Blue', 'hex': '#0000FF', 'rgb': {'r'...
5   {'name': 'Yellow', 'hex': '#FFFF00', 'rgb': {'...
6   {'name': 'Cyan', 'hex': '#00FFFF', 'rgb': {'r'...
7   {'name': 'Magenta', 'hex': '#FF00FF', 'rgb': {...
8   {'name': 'Orange', 'hex': '#FFA500', 'rgb': {'...
9   {'name': 'Pink', 'hex': '#FFC0CB', 'rgb': {'r'...
10  {'name': 'Purple', 'hex': '#800080', 'rgb': {'...
11  {'name': 'Violet', 'hex': '#EE82EE', 'rgb': {'...
12  {'name': 'Brown', 'hex': '#A52A2A', 'rgb': {'r...
13  {'name': 'Maroon', 'hex': '#800000', 'rgb': {'...
14  {'name': 'Olive', 'hex': '#808000', 'rgb': {'r...
15  {'name': 'Teal', 'hex': '#008080', 'rgb': {'r'...
16  {'name': 'Navy', 'hex': '#000080', 'rgb': {'r'...
17  {'name': 'Gray', 'hex': '#808080', 'rgb': {'r'...
18  {'name': 'Silver', 'hex': '#C0C0C0', 'rgb': {'...
19  {'name': 'Lime', 'hex': '#32CD32', 'rgb': {'r'...
20  {'name': 'Aqua', 'hex': '#00CED1', 'rgb': {'r'...
21  {'name': 'Coral', 'hex': '#FF7F50', 'rgb': {'r...
22  {'name': 'Salmon', 'hex': '#FA8072', 'rgb': {'...
23  {'name': 'Khaki', 'hex': '#F0E68C', 'rgb': {'r...
24  {'name': 'Plum', 'hex': '#DDA0DD', 'rgb': {'r'...
25  {'name': 'Gold', 'hex': '#FFD700', 'rgb': {'r'...
26  {'name': 'Crimson', 'hex': '#DC143C', 'rgb': {...
27  {'name': 'Indigo', 'hex': '#4B0082', 'rgb': {'...
28  {'name': 'Turquoise', 'hex': '#40E0D0', 'rgb':...
29  {'name': 'Ivory', 'hex': '#FFFFF0', 'rgb': {'r...
30  {'name': 'Beige', 'hex': '#F5F5DC', 'rgb': {'r...
31  {'name': 'Lavender', 'hex': '#E6E6FA', 'rgb': ...
32  {'name': 'Mint', 'hex': '#98FF98', 'rgb': {'r'...
33  {'name': 'Peach', 'hex': '#FFCBA4', 'rgb': {'r...
34  {'name': 'Slate', 'hex': '#708090', 'rgb': {'r...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import files
uploaded  = files.upload()

uploaded

Saving name.csv to name (1).csv

{'name (1).csv': b'value\r\nbarjraj\r\nramdin verma\r\nsharat chandran\r\nbirender mandal\r\namit\r\nkushal\r\nkasid\r\nshiv prakash\r\nvikram singh\r\nsanjay\r\nabhi\r\nram dutt gupta\r\nkhadak singh\r\ngurmit singh\r\nchanderpal\r\naman\r\nkhursid\r\nrajeev\r\ndurgesh\r\nnahar singh\r\nram kumar\r\nsunder paal\r\nmaansingh aswal\r\nrohit\r\nrohit\r\nsparsh\r\nsantosh\r\nsantosh\r\npunit khandelwal\r\ndinesh\r\ngulshan\r\narvind kumar yadav\r\nnausad\r\ngurmit singh\r\nshiv shakti singh\r\nmoti lal\r\nkausal kumar\r\nrohit\r\nrohit\r\nmohabbat ali\r\nraj kumar\r\njaswant singh\r\nchotelal\r\namit\r\nrupesh\r\nmidda\r\ndharam singh\r\nram singh\r\npreetam kumar\r\nram kumar\r\nsarain\r\npankaj kumar\r\nsheak shakir\r\nriyasat ali\r\nvinit katariya\r\nsumit\r\narindra\r\nkali charan\r\nbadshya khan\r\nvikash\r\ndevinder chadda\r\naman\r\nmohan singh\r\nhemant\r\nshivam\r\nyash mittal\r\naakash\r\nchandesh\r\nsumit mitra\r\nsupriyal sen\r\npooran chand sharma\r\nirfan\r\nazaruddin\r\nmukul yadav\r\npooran chand sharma\r\nmanoj\r\nsanjay charee\r\nraja babu\r\npawan\r\nsandeep\r\nrajkumar chawla\r\nparvesh\r\nmohd ataullah\r\nneeraj kumar\r\njamil khan\r\nyogita\r\nrijul aggarwal\r\nmohd shakib\r\nrahul kumar\r\nrajender\r\nsuraj\r\nrizwan\r\nsandeep\r\nmd mustafa\r\nhar parsad\r\ndeepak\r\nrahul\r\nabhishekh\r\nshelender yadav\r\nsanjay\r\n'}

**EXPLORING PANDAS**

In [ ]:

df = json_data
display(df.head())
display(df.columns)
display(df.info())

                                              colors
0  {'name': 'Black', 'hex': '#000000', 'rgb': {'r...
1  {'name': 'White', 'hex': '#FFFFFF', 'rgb': {'r...
2  {'name': 'Red', 'hex': '#FF0000', 'rgb': {'r':...
3  {'name': 'Green', 'hex': '#00FF00', 'rgb': {'r...
4  {'name': 'Blue', 'hex': '#0000FF', 'rgb': {'r'...

Index(['colors'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   colors  35 non-null     object
dtypes: object(1)
memory usage: 412.0+ bytes

None

In [ ]:
df.isnull().sum()

colors    0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.isna()

    colors
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False

**USE INPLACE TO SAVE THE CHANGES IN DATA **

Selecting Data

In [ ]:
df = name
display(df)
df['value']

              value
0           barjraj
1      ramdin verma
2   sharat chandran
3   birender mandal
4              amit
..              ...
95           deepak
96            rahul
97        abhishekh
98  shelender yadav
99           sanjay

[100 rows x 1 columns]

0             barjraj
1        ramdin verma
2     sharat chandran
3     birender mandal
4                amit
           ...
95             deepak
96              rahul
97          abhishekh
98    shelender yadav
99             sanjay
Name: value, Length: 100, dtype: object

In [ ]:
airplane = pd.read_csv("/content/Airline Dataset.csv")
display(airplane)
airplane['Age'] = airplane['Age'].astype('string')
display(airplane)



print(airplane.dtypes)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed

Passenger ID                     int64
First Name                      object
Last Name                       object
Gender                          object
Age                     string[python]
Nationality                     object
Airport Name                    object
Airport Country Code            object
Country Name                    object
Airport Continent               object
Continents                      object
Departure Date                  object
Arrival Airport                 object
Pilot Name                      object
Flight Status                   object
dtype: object

**SORTING DATA SET **

In [ ]:
airplane['Name_Age'] = airplane['First Name'] + " " + airplane['Age']
display(airplane)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Name_Age
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time,Edithe 62
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time,Elwood 62
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time,Darby 67
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed,Dominica 71
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time,Bay 21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled,Gareth 85
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled,Kasey 19
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time,Darrin 65
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled,Gayle 34
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed,Wilhelmine 10

In [ ]:
airplane.sort_values(by='Age', ascending=False)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Name_Age
61815,70951,Aaren,Tours,Female,11,Malawi,Miyakejima Airport,JP,Japan,AS,Asia,1/30/2022,MYE,Aaren Tours,Delayed,Aaren 11
2520,30606,Aaren,Kohnen,Female,89,Croatia,Srednekolymsk Airport,RU,Russian Federation,EU,Europe,9/21/2022,SEK,Aaren Kohnen,Delayed,Aaren 89
20723,32541,Aaren,Ayre,Female,2,Indonesia,Dinard-Pleurtuit-Saint-Malo Airport,FR,France,EU,Europe,5/26/2022,DNR,Aaren Ayre,Cancelled,Aaren 2
71656,30131,Aaren,Hornig,Female,60,Indonesia,Ndalatandos Airport,AO,Angola,AF,Africa,4/8/2022,NDF,Aaren Hornig,Delayed,Aaren 60
12909,57743,Aaren,Boyse,Female,84,China,Richards Bay Airport,ZA,South Africa,AF,Africa,6/25/2022,RCB,Aaren Boyse,Cancelled,Aaren 84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27792,26926,Zuzana,Nutbeem,Female,65,Portugal,Palma De Mallorca Airport,ES,Spain,EU,Europe,9/12/2022,PMI,Zuzana Nutbeem,Cancelled,Zuzana 65
73982,39953,Zuzana,Wingrove,Female,88,Russia,Viveros Island Airport,PA,Panama,NAM,North America,4/6/2022,IVI,Zuzana Wingrove,Delayed,Zuzana 88
57821,96261,Zuzana,Tibbles,Female,9,Iran,Comodoro Pierrestegui Airport,AR,Argentina,SAM,South America,9/7/2022,COC,Zuzana Tibbles,On Time,Zuzana 9
40722,84173,Zuzana,Bruneton,Female,78,Albania,Moro Airport,PG,Papua New Guinea,OC,Oceania,3/30/2022,MXH,Zuzana Bruneton,On Time,Zuzana 78
85016,72023,Zuzana,Hurdedge,Female,55,Bangladesh,Kenai Municipal Airport,US,United States,NAM,North America,2/8/2022,ENA,Zuzana Hurdedge,Cancelled,Zuzana 55

In [ ]:
airplane.sort_values(by='First Name')

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Name_Age
61815,70951,Aaren,Tours,Female,11,Malawi,Miyakejima Airport,JP,Japan,AS,Asia,1/30/2022,MYE,Aaren Tours,Delayed,Aaren 11
2520,30606,Aaren,Kohnen,Female,89,Croatia,Srednekolymsk Airport,RU,Russian Federation,EU,Europe,9/21/2022,SEK,Aaren Kohnen,Delayed,Aaren 89
20723,32541,Aaren,Ayre,Female,2,Indonesia,Dinard-Pleurtuit-Saint-Malo Airport,FR,France,EU,Europe,5/26/2022,DNR,Aaren Ayre,Cancelled,Aaren 2
71656,30131,Aaren,Hornig,Female,60,Indonesia,Ndalatandos Airport,AO,Angola,AF,Africa,4/8/2022,NDF,Aaren Hornig,Delayed,Aaren 60
12909,57743,Aaren,Boyse,Female,84,China,Richards Bay Airport,ZA,South Africa,AF,Africa,6/25/2022,RCB,Aaren Boyse,Cancelled,Aaren 84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27792,26926,Zuzana,Nutbeem,Female,65,Portugal,Palma De Mallorca Airport,ES,Spain,EU,Europe,9/12/2022,PMI,Zuzana Nutbeem,Cancelled,Zuzana 65
73982,39953,Zuzana,Wingrove,Female,88,Russia,Viveros Island Airport,PA,Panama,NAM,North America,4/6/2022,IVI,Zuzana Wingrove,Delayed,Zuzana 88
57821,96261,Zuzana,Tibbles,Female,9,Iran,Comodoro Pierrestegui Airport,AR,Argentina,SAM,South America,9/7/2022,COC,Zuzana Tibbles,On Time,Zuzana 9
40722,84173,Zuzana,Bruneton,Female,78,Albania,Moro Airport,PG,Papua New Guinea,OC,Oceania,3/30/2022,MXH,Zuzana Bruneton,On Time,Zuzana 78
85016,72023,Zuzana,Hurdedge,Female,55,Bangladesh,Kenai Municipal Airport,US,United States,NAM,North America,2/8/2022,ENA,Zuzana Hurdedge,Cancelled,Zuzana 55

In [ ]:
airplane.rename(columns={'Last Name': 'Sir Name'}, inplace=True)
airplane

,Passenger ID,First Name,Sir Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Name_Age
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time,Edithe 62
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time,Elwood 62
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time,Darby 67
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed,Dominica 71
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time,Bay 21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled,Gareth 85
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled,Kasey 19
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time,Darrin 65
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled,Gayle 34
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed,Wilhelmine 10

In [ ]:
airplane[airplane["Country Name"] == "United States"]

,Passenger ID,First Name,Sir Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status,Name_Age
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time,Edithe 62
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time,Bay 21
14,53524,Amberly,Handling,Female,32,China,Farmington Regional Airport,US,United States,NAM,North America,3/7/2022,FAM,Amberly Handling,Delayed,Amberly 32
20,61145,Paige,Hayhow,Male,24,Sweden,Crested Butte Airpark,US,United States,NAM,North America,2/19/2022,CSE,Paige Hayhow,Delayed,Paige 24
24,40864,Sayre,Stroyan,Male,87,Indonesia,Elkhart Municipal Airport,US,United States,NAM,North America,3/20/2022,EKI,Sayre Stroyan,Cancelled,Sayre 87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98590,36988,Kath,Palfreman,Female,31,Japan,Elizabeth Field,US,United States,NAM,North America,6/28/2022,FID,Kath Palfreman,On Time,Kath 31
98592,97507,Benjie,Garrioch,Male,2,Peru,Port Heiden Airport,US,United States,NAM,North America,9/14/2022,PTH,Benjie Garrioch,On Time,Benjie 2
98604,22436,Freddie,Landrean,Female,47,Brazil,St Cloud Regional Airport,US,United States,NAM,North America,2/8/2022,STC,Freddie Landrean,On Time,Freddie 47
98605,68629,Morganne,Ockenden,Female,7,China,Newport Municipal Airport,US,United States,NAM,North America,9/7/2022,ONP,Morganne Ockenden,On Time,Morganne 7
98612,26208,Ody,Tineman,Male,82,Indonesia,Five Mile Airport,US,United States,NAM,North America,3/17/2022,FMC,Ody Tineman,Delayed,Ody 82