<a href="https://colab.research.google.com/github/mrJay188/AI-ML/blob/main/Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

| Parameter    | Default  | Purpose                               | When to Use                                           |
| ------------ | -------- | ------------------------------------- | ----------------------------------------------------- |
| `data`       | Required | Input DataFrame/Series                | Always                                                |
| `prefix`     | `None`   | Custom prefix for dummy columns       | Avoid column name conflicts                           |
| `prefix_sep` | `'_'`    | Separator between prefix and category | Customize column names                                |
| `dummy_na`   | `False`  | Create a separate column for NaN      | Missing values are meaningful                         |
| `columns`    | `None`   | Encode only specified columns         | Selective encoding                                    |
| `sparse`     | `False`  | Use sparse storage                    | Very large datasets with many zeros                   |
| `drop_first` | `False`  | Drop the first dummy column           | Linear/Logistic Regression to avoid multicollinearity |
| `dtype`      | `None`   | Output data type                      | Use `int` or `uint8` for ML datasets                  |

In [ ]:
import pandas as pd

In [ ]:
pd.get_dummies(
    data,
    prefix=None,
    prefix_sep='_',
    dummy_na=False,
    columns=None,
    sparse=False,
    drop_first=False,
    dtype=None
  )

NameError: name 'data' is not defined

   pd.get_dummies(
    data,
    prefix=None,
    prefix_sep='_',
    dummy_na=False,
    columns=None,
    sparse=False,
    drop_first=False,
    dtype=None
  )

In [ ]:
#pd.get_dummies()

In [ ]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green']
})

pd.get_dummies(df)

In [ ]:
pd.get_dummies(df, dtype=int)

# 2. prefix
Purpose

Adds a custom prefix before the generated column names.

Default:
prefix=None

In [ ]:
prefix=None

In [ ]:
pd.get_dummies(df, dtype=int)

In [ ]:
pd.get_dummies(df, prefix='clr', dtype=int)

In [ ]:
df = pd.DataFrame({
    'Color':['Red','Blue'],
    'Size':['S','M']
})


df

  Color Size
0   Red    S
1  Blue    M

In [ ]:
pd.get_dummies(
    df,
    prefix=['C','S'],
    dtype=int
)

   C_Blue  C_Red  S_M  S_S
0       0      1    0    1
1       1      0    1    0

## 3. prefix_sep

In [ ]:
pd.get_dummies(
    df,
    prefix='Color',
    prefix_sep='-',
    dtype=int
)

   Color-Blue  Color-Red  Color-M  Color-S
0           0          1        0        1
1           1          0        1        0

## 4. dummy_na

Purpose

Creates a separate column for missing (NaN) values.

In [ ]:
df1 = pd.DataFrame({
    'Color':['Red','Blue',None]
})

In [ ]:
pd.get_dummies(df1, dtype=int)

   Color_Blue  Color_Red
0           0          1
1           1          0
2           0          0

## 5. columns

Purpose

Specifies which columns should be encoded.

Default
columns=None

In [ ]:
df = pd.DataFrame({
    'Age':[20,21],
    'Color':['Red','Blue'],
    'Gender':['M','F']
})

In [ ]:
df

   Age Color Gender
0   20   Red      M
1   21  Blue      F

In [ ]:
pd.get_dummies(
    df,
    columns=['Color'],
    dtype=int
)

   Age Gender  Color_Blue  Color_Red
0   20      M           0          1
1   21      F           1          0

In [ ]:
pd.get_dummies(
    df,
    columns=['Color','Gender'],
    dtype=int
)

   Age  Color_Blue  Color_Red  Gender_F  Gender_M
0   20           0          1         0         1
1   21           1          0         1         0

## 6. sparse
Purpose

Stores dummy variables in a sparse format to save memory.

Default : False

Useful when

- Millions of rows
- Thousands of categories
- Mostly 0 values

In [ ]:
pd.get_dummies(
    df,
    sparse=True
)

## 7. drop_first
Purpose

Drops the first dummy column.

Default

In [ ]:
df = pd.DataFrame({
    'Gender':['Male','Female','Male']
})

In [ ]:
pd.get_dummies(df, dtype=int)

In [ ]:
pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)