<a href="https://colab.research.google.com/github/mrJay188/AI-ML/blob/main/Transformers_in_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PowerTransformer

In [ ]:
df = pd.DataFrame({'House_prices':[100000,120000,150000,20000,80000,250000]})

In [ ]:
df

   House_prices
0        100000
1        120000
2        150000
3         20000
4         80000
5        250000

In [ ]:
df['log_prices'] = np.log1p(df['House_prices'])

In [ ]:
df

   House_prices  log_prices
0        100000   11.512935
1        120000   11.695255
2        150000   11.918397
3         20000    9.903538
4         80000   11.289794
5        250000   12.429220

In [ ]:
pt = PowerTransformer(method="yeo-johnson")
df['Prower_prices'] = pt.fit_transform(df[['House_prices']])

In [ ]:
df

   House_prices  log_prices  Prower_prices
0        100000   11.512935      -0.140862
1        120000   11.695255       0.140619
2        150000   11.918397       0.526754
3         20000    9.903538      -1.694195
4         80000   11.289794      -0.448359
5        250000   12.429220       1.616042